'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './component/navbar';
import Footer from './component/footer';
import { AppProvider } from './conetext/productConetext';
import { FilterContextProvider } from "./conetext/FilterContext";
import { CartProvider } from './conetext/CartContext';
import { Auth0Provider } from '@auth0/auth0-react';
import { ThemeProvider } from '@mui/material/styles';
import theme  from './config/theme';


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Lenin ECommerce App',
//   description: 'Generated by create next app',
// }
const domain = process.env.REACT_APP_AUTH;
const clientId = process.env.REACT_APP_CLIENT

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Auth0Provider
        domain= {domain}
        clientId={clientId}
        authorizationParams={{
          // redirect_uri: window?.location.origin
        }}
    >
      <ThemeProvider theme={theme}>
      <AppProvider>
    <FilterContextProvider>
      <CartProvider>

        <Navbar/>

     
        {children}
        <Footer/>
        </CartProvider>
    </FilterContextProvider>

        </AppProvider>
        </ThemeProvider>
        </Auth0Provider>
        </body>
    </html>
  )
}
