
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './component/navbar';
import Footer from './component/footer';
import { AppProvider } from './conetext/productConetext';
import { FilterContextProvider } from "./conetext/FilterContext";
import { CartProvider } from './conetext/CartContext';
import { Auth0Provider } from '@auth0/auth0-react';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lenin ECommerce App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Auth0Provider
        domain="dev-l8w1sw2luedpedny.us.auth0.com"
        clientId="RVH4i3ZmvwmQQANZXrHIX0OoxTPNxQB2"
        authorizationParams={{
          redirect_uri: window.location.origin
        }}
    >
      <AppProvider>
    <FilterContextProvider>
      <CartProvider>

        <Navbar/>
        {children}
        <Footer/>
        </CartProvider>
    </FilterContextProvider>

        </AppProvider>
        </Auth0Provider>
        </body>
    </html>
  )
}
